version: '3.7'
services:
  web:
    build: 
      context: .
      dockerfile: ./docker/app.Dockerfile
    command: python main.py
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./src/:/app/
    ports:
      - 5000:5000
    depends_on:
      - celery
  celery:
    build: 
      context: .
      dockerfile: ./docker/celery.Dockerfile
    command: celery worker -A main.celery --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./src/:/app/
    depends_on:
      - redis
  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379    

